image: herzog31/corvi-build:latest

variables:
  CGO_ENABLED: "0"
  GO_EXTLINK_ENABLED: "0"

stages:
  - test
  - build

backend_test:
  stage: test
  script:
    - "rm -rf $GOPATH/src/marb.ec"
    - "mkdir -p $GOPATH/src/marb.ec/corvi-backend"
    - "mv $CI_PROJECT_DIR/backend/* $GOPATH/src/marb.ec/corvi-backend"
    - "cd $GOPATH/src/marb.ec/corvi-backend"
    - "ls -aslh"
    - "go get -t -v -insecure ./..."
    - "go test -bench=. -benchmem -v -cover -coverprofile=coverage.out -covermode=count"

build_darwin:
  stage: build
  script:
    - "# Cleanup"
    - "rm -rf $GOPATH/src/marb.ec"
    - "# Copy Backend"
    - "mkdir -p $GOPATH/src/marb.ec/corvi-backend"
    - "mv $CI_PROJECT_DIR/backend/* $GOPATH/src/marb.ec/corvi-backend"
    - "cd $GOPATH/src/marb.ec/corvi-backend"
    - "ls -aslh"
    - "# Build Backend"
    - "go get -t -v -insecure ./..."
    - "gox -osarch=\"darwin/amd64\" -output=\"dist/corvi-backend\""
    - "cd dist"
    - "ls -aslh"
    - "# Prepare electron build"
    - "rm -rf $CI_PROJECT_DIR/build-darwin"
    - "mkdir -p $CI_PROJECT_DIR/build-darwin/src"
    - "mv $CI_PROJECT_DIR/frontend $CI_PROJECT_DIR/build-darwin/src"
    - "mv $GOPATH/src/marb.ec/corvi-backend/dist/corvi-backend $CI_PROJECT_DIR/build-darwin/src"
    - "mv $CI_PROJECT_DIR/electron/* $CI_PROJECT_DIR/build-darwin/src"
    - "mv $CI_PROJECT_DIR/build-darwin/src/package.json $CI_PROJECT_DIR/build-darwin/"
    - "cd $CI_PROJECT_DIR/build-darwin"
    - "# Electron build"
    - "electron-packager . Corvi --platform=darwin --arch=x64 --out=out/ --ignore=\"(/node_modules|/out)\" --asar=false"
    - "ls -aslhR"