image: herzog31/corvi-build:latest

stages:
  - setup
  - test
  - build-backend
  - build-electron
  - deploy
  
cleanup:
  stage: setup
  script:
    - "rm -rf $GOPATH/src/marb.ec"

setup_go_project:
  stage: setup
  script:
    - "mkdir -p $GOPATH/src/marb.ec/corvi-backend"
    - "mv /builds/marbec/corvi/backend/* $GOPATH/src/marb.ec/corvi-backend"
    - "cd $GOPATH/src/marb.ec/corvi-backend"
    - "ls -a"

backend_test:
  stage: test
  script:
    - "ls -a"
    - "go get -t -v -insecure ./..."
    - "go test -bench=. -benchmem -v -cover -coverprofile=coverage.out -covermode=count"