image: herzog31/corvi-build:latest

variables:
  CGO_ENABLED: "0"
  GO_EXTLINK_ENABLED: "0"

stages:
  - test
  - build

backend_test:
  stage: test
  script:
    - "rm -rf $GOPATH/src/marb.ec"
    - "mkdir -p $GOPATH/src/marb.ec/corvi-backend"
    - "mv /builds/marbec/corvi/backend/* $GOPATH/src/marb.ec/corvi-backend"
    - "cd $GOPATH/src/marb.ec/corvi-backend"
    - "ls -aslh"
    - "go get -t -v -insecure ./..."
    - "go test -bench=. -benchmem -v -cover -coverprofile=coverage.out -covermode=count"

build_darwin:
  stage: build
  script:
    - "rm -rf $GOPATH/src/marb.ec"
    - "mkdir -p $GOPATH/src/marb.ec/corvi-backend"
    - "mv /builds/marbec/corvi/backend/* $GOPATH/src/marb.ec/corvi-backend"
    - "cd $GOPATH/src/marb.ec/corvi-backend"
    - "ls -aslh"
    - "go get -t -v -insecure ./..."
    - "gox -osarch=darwin/amd64 -output=dist/corvi-backend"
    - "cd dist"
    - "ls -aslh"